webapp/config/routes.rb
Rails.application.routes.draw do
  root to: "ir_signals#index"

  scope "/webhooks" do
    post "nec_code" => "webhooks#nec_code"
  end

  resources :ir_signals do
    member do
      get  :nec_code_status
      post :nec_code_trigger
    end
  end
end

webapp/app/models/ir_device.rb
class IrDevice
  NAME = "plughackathon"

  class << self
    def send_nec_code(nec_code)
      Particle.device(NAME).function("sendIRSignal", nec_code)
    end

    def start_emitting_ir_signals
      Particle.device(NAME).function("emitIRSignal", "start")
    end

    def stop_emitting_ir_signals
      Particle.device(NAME).function("emitIRSignal", "stop")
    end
  end
end

webapp/app/models/ir_signal.rb
class IrSignal < ActiveRecord::Base
  scope :incomplete, -> { where(nec_code: nil) }
end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

webapp/app/controllers/ir_signals_controller.rb
class IrSignalsController < ApplicationController
  def index
    @ir_signals = IrSignal.all
  end

  def new
    @ir_signal = IrSignal.new
  end

  def create
    @ir_signal = IrSignal.new(ir_signal_params)
    if @ir_signal.save
      IrDevice.start_emitting_ir_signals
      redirect_to nec_code_status_ir_signal_url(@ir_signal)
    else
      render :new
    end
  end

  def destroy
    @ir_signal = IrSignal.find(params[:id])
    @ir_signal.destroy
    redirect_to ir_signals_url
  end

  def nec_code_status
    @ir_signal = IrSignal.find(params[:id])
    if @ir_signal.nec_code?
      @redirect_url = root_url
    else
      @redirect_url = nec_code_status_ir_signal_url(@ir_signal)
    end
    @redirect_delay = 2
  end

  def nec_code_trigger
    @ir_signal = IrSignal.find(params[:id])
    IrDevice.send_nec_code(@ir_signal.nec_code)
    redirect_to ir_signals_url
  end

  private

  def ir_signal_params
   params.require(:ir_signal).permit(:name)
  end
end

webapp/app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def nec_code
    @ir_signal = IrSignal.incomplete.first
    @ir_signal.update_attribute :nec_code, params[:data].chomp
    IrDevice.stop_emitting_ir_signals
    head :ok
  end
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/views/ir_signals/index.html.erb
<div class="IrSignals">
<% @ir_signals.each do |ir_signal| %>
<div class="IrSignal">
  <%= link_to "&nbsp;".html_safe, ir_signal_path(ir_signal), class: "remove", confirm: "Are you sure?", method: :delete %>
  <%= link_to ir_signal.name, nec_code_trigger_ir_signal_path(ir_signal), class: "name", method: :post %>
</div>
<% end %>
</div>

<%= link_to "+", new_ir_signal_path, class: "addButton" %>

webapp/app/views/ir_signals/nec_code_status.html.erb
<% if @ir_signal.nec_code? %>

<h2>You're all set!
<div class="RoundBigButton green">Done</div>

<% else %>

  <h2>Please press the button on your remote</h2>
  <div class="RoundBigButton red">Recording</div>

<% end %>

webapp/app/views/ir_signals/new.html.erb
<div class="IrSignalAdd">
  <%= form_for @ir_signal do |f| %>
  <div class="name">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.button "Record", class: "RoundBigButton" %>
  </div>
  <% end %>
</div>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "IR-remote Webapp" %></title>

    <% if @redirect_url %>
    <meta http-equiv='refresh' content='<%= @redirect_delay -%>;url=<%= @redirect_url -%>'>
    <% end %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>